### ISSUE TITLE
‘MIG_MON_VERSION’ undeclared when compile mig_mon tool

### ISSUE THREAD

**Issue by leexiaohui32** [xzpeter/mig_mon#4]
[root@dell-per760-25 mig_mon]# gcc downtime.c mig_mon.c utils.c mm_dirty.c vm.c -o mig_mon -lpthread
mig_mon.c: In function ‘version’:
mig_mon.c:16:29: error: ‘MIG_MON_VERSION’ undeclared (first use in this function)
   16 |     printf("Version: %s\n", MIG_MON_VERSION);
      |                             ^~~~~~~~~~~~~~~
mig_mon.c:16:29: note: each undeclared identifier is reported only once for each function it appears in
mm_dirty.c: In function ‘mon_mm_dirty’:
mm_dirty.c:123:38: error: ‘MIG_MON_VERSION’ undeclared (first use in this function)
  123 |     printf("Binary version: \t%s\n", MIG_MON_VERSION);
      |                                      ^~~~~~~~~~~~~~~
mm_dirty.c:123:38: note: each undeclared identifier is reported only once for each function it appears in

**Comment by leexiaohui32** [comment]
@xzpeter , do we need the MIG_MON_VERSION? 
I define MIG_MON_VERSION in mig_mon.h as a workaround :
`#define  MIG_MON_VERSION  "v0.2.2"
`

**Comment by xzpeter** [comment]
@leexiaohui32, I just switched to use meson for the build system..

And btw there used to be a makefile, so you don't need to invoke gcc every time.  You can always use "make" to build mig_mon (before/after the meson change).

For the latest repo, you'll also need "sudo dnf install meson" to make it work.

**Comment by xzpeter** [comment]
meson will define the version macro when building.

**Comment by leexiaohui32** [comment]
@xzpeter , it works well after using meson. Thanks very much.
